# Setup
title:               Lipshutz Lab
tagline:             Department of Neuroscience, Baylor College of Medicine
description:         
url:                 https://lipshutzlab.com
baseurl:             ''
paginate:            5
permalink:           pretty
email:               David.Lipshutz@bcm.edu

include:
  - _pages

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0