# Setup
title:               Lipshutz Lab
tagline:             Department of Neuroscience, Baylor College of Medicine
description:         
url:                 https://lipshutzlab.com
baseurl:             ''
paginate:            5
permalink:           pretty
email:               lipshutz@gmail.com

include:
  - _pages

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
